---
- hosts: localhost
  vars_files:
    - vars/main.yml
  environment:
    XDG_CONFIG_HOME: '{{ xdg_config_home }}'
    XDG_DATA_HOME: '{{ xdg_data_home | expandvars }}'
    XDG_CACHE_HOME: '{{ xdg_cache_home | expandvars }}'
    ASDF_DIR: '{{ asdf_dir | expandvars }}'
    ASDF_DATA_DIR: '{{ asdf_data_dir | expandvars }}'

  roles:
    - zsh
    - asdf
    - tmux
    - neovim
    - alacritty
    - fonts
    - vscode
