---
- hosts: localhost

  vars:
    xdg_config_home: '$HOME/.config'
    xdg_data_home: '$XDG_CONFIG_HOME/local/share'
    xdg_cache_home: '$XDG_CONFIG_HOME/cache'
    zsh_dir: '$XDG_CONFIG_HOME/zsh'
    asdf_dir: '$XDG_CONFIG_HOME/asdf'
    asdf_data_dir: '$XDG_DATA_HOME/asdf'
  environment:
    XDG_CONFIG_HOME: '{{ xdg_config_home }}'
    XDG_DATA_HOME: '{{ xdg_data_home | expandvars }}'
    XDG_CACHE_HOME: '{{ xdg_cache_home | expandvars }}'
    ASDF_DIR: '{{ asdf_dir | expandvars }}'
    ASDF_DATA_DIR: '{{ asdf_data_dir | expandvars }}'

  roles:
    - zsh
    - asdf
    - tmux
    - neovim
    - alacritty
    - fonts
    - vscode
