---
- hosts: localhost
  vars_files:
    - vars/main.yml
  environment:
    XDG_CONFIG_HOME: '{{ xdg_config_home }}'
    XDG_DATA_HOME: '{{ xdg_data_home }}'
    XDG_CACHE_HOME: '{{ xdg_cache_home }}'

  roles:
    - zsh
    - asdf
    - tmux
    - neovim
    - fonts
