---
- hosts: localhost

  vars:
    xdg_config_home: '$HOME/.config'
    xdg_data_home: '$XDG_CONFIG_HOME/local/share'
    xdg_cache_home: '$XDG_CONFIG_HOME/cache'
    zsh_dir: '$XDG_CONFIG_HOME/zsh'
    asdf_dir: '$XDG_CONFIG_HOME/asdf'
    asdf_data_dir: '$XDG_DATA_HOME/asdf'
    tmux_dir: '$XDG_CONFIG_HOME/tmux'
    nvim_dir: '$XDG_CONFIG_HOME/nvim'
    alacritty_dir: '$XDG_CONFIG_HOME/alacritty'
    vscode_dir: '$XDG_CONFIG_HOME/vscode'

  environment:
    # Need to explicitly use HOME env to make it work on VM
    XDG_CONFIG_HOME: '{{ ansible_env.HOME }}/.config'
    XDG_DATA_HOME: '{{ ansible_env.HOME }}/.config/local/share'
    XDG_CACHE_HOME: '{{ ansible_env.HOME }}/.config/cache'
    ASDF_DIR: '{{ ansible_env.HOME }}/.config/asdf'
    ASDF_DATA_DIR: '{{ ansible_env.HOME }}/.config/local/share/asdf'

  roles:
    - zsh
    - asdf
    - fonts
    - tmux
    - neovim
    - alacritty
    - vscode
    - postman
