---
- name: Install vscode for Debian
  become: true
  community.general.snap:
    name: code
    classic: true
  when: ansible_facts.os_family == 'Debian'

- name: Install vscode for Darwin
  community.general.homebrew:
    name: visual-studio-code
    install_options: cask
  when: ansible_facts.os_family == 'Darwin'

- name: Ensure directories exist
  ansible.builtin.file:
    path: '{{ xdg_config_home }}/vscode/{{ item }}'
    state: directory
  loop:
    - data/User
    - extensions

- name: Create a default vscode settings file
  ansible.builtin.copy:
    src: settings.json
    dest: '{{ xdg_config_home }}/vscode/data/User/settings.json'
    backup: true
    mode: 'u=rw,go=r'

- name: Install vscode extensions
  ansible.builtin.command: code \
    --user-data-dir {{ xdg_config_home }}/vscode/data \
    --extensions-dir {{ xdg_config_home }}/vscode/extensions \
    --install-extension {{ item }}
  loop: '{{ vscode_extensions }}'

- name: Add code alias
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir | expandvars }}/aliases'
    marker: '{mark} vscode'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: alias code='code
      --user-data-dir $XDG_CONFIG_HOME/vscode/data
      --extensions-dir $XDG_CONFIG_HOME/vscode/extensions'
