---
- name: Install vscode for Ubuntu
  become: true
  community.general.snap:
    name: code
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install vscode for MacOS
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Ensure directories exist
  ansible.builtin.file:
    path: '{{ vscode_dir }}/{{ item }}'
    state: directory
  loop:
    - data/User
    - extensions

- name: Create a default vscode settings file
  ansible.builtin.copy:
    src: settings.json
    dest: '{{ vscode_dir }}/data/User/settings.json'
    backup: true
    mode: 'u=rw,go=r'

- name: Install vscode extensions
  ansible.builtin.command: code \
    --user-data-dir {{ vscode_dir }}/data \
    --extensions-dir {{ vscode_dir }}/extensions \
    --install-extension {{ item }}
  loop: '{{ vscode_extensions }}'

- name: Add code alias
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir }}/aliases'
    marker: '{mark} vscode'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: alias code='code
      --user-data-dir {{ vscode_dir }}/data
      --extensions-dir {{ vscode_dir }}/extensions'
