---
- name: Install vscodium for Ubuntu
  become: true
  community.general.snap:
    name: codium
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install vscodium for MacOS
  community.general.homebrew_cask:
    name: vscodium
    state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Ensure directories exist
  ansible.builtin.file:
    path: '{{ vscodium_dir }}/{{ item }}'
    state: directory
  loop:
    - data/User
    - extensions

- name: Create vscodium user config files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ vscodium_dir }}/data/User/{{ item }}'
    backup: true
    mode: 'u=rw,go=r'
  loop:
    - keybindings.json
    - settings.json

- name: Install vscodium extensions
  ansible.builtin.command: codium \
    --user-data-dir {{ vscodium_dir }}/data \
    --extensions-dir {{ vscodium_dir }}/extensions \
    --install-extension {{ item }}
  loop: '{{ vscodium_extensions }}'

- name: Create user data symbolic link
  ansible.builtin.file:
    src: '{{ vscodium_dir }}/data'
    dest: '{{ ansible_env.HOME }}/Library/Application Support/VSCodium'
    state: link
  when: ansible_facts.distribution == 'MacOSX'

- name: Create extensions symbolic link
  ansible.builtin.file:
    src: '{{ vscodium_dir }}/extensions'
    dest: '{{ ansible_env.HOME }}/.vscode-oss/extensions'
    state: link
  when: ansible_facts.distribution == 'MacOSX'

- name: Add code alias for MacOS
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir }}/aliases'
    marker: '{mark} vscodium'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: alias code=codium
  when: ansible_facts.distribution == 'MacOSX'

- name: Add code alias for Ubuntu
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir }}/aliases'
    marker: '{mark} vscodium'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: alias code='codium
      --user-data-dir {{ vscodium_dir }}/data
      --extensions-dir {{ vscodium_dir }}/extensions'
  when: ansible_facts.distribution == 'Ubuntu'
