---
- name: Install asdf dependencies for Debian
  become: true
  ansible.builtin.package:
    name: '{{ asdf_debian_dependencies }}'
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install asdf dependencies for Darwin
  ansible.builtin.package:
    name: '{{ asdf_darwin_dependencies }}'
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Clone asdf repo
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '{{ ansible_facts.user_dir }}/.asdf'
    version: v0.12.0

- name: Insert asdf config .zshrc
  ansible.builtin.blockinfile:
    path: '{{ ansible_facts.user_dir }}/.zshrc'
    block: |
      # Load asdf
      . "$HOME/.asdf/asdf.sh"
      # append completions to fpath
      fpath=(${ASDF_DIR}/completions $fpath)
      # initialise completions with ZSH's compinit
      autoload -Uz compinit && compinit

- name: Install asdf plugins
  ansible.builtin.shell: |
    export ASDF_DIR={{ ansible_facts.user_dir }}/.asdf
    . {{ ansible_facts.user_dir }}/.asdf/asdf.sh
    asdf plugin add {{ item.name }} || true
    asdf install {{ item.name }} {{ item.version }}
    asdf global {{ item.name }} {{ item.version }}
  loop: '{{ asdf_plugins|flatten(levels=1) }}'
