---
- name: Install asdf dependencies for Ubuntu
  become: true
  ansible.builtin.package:
    name: '{{ asdf_ubuntu_dependencies }}'
    state: present
  when: ansible_facts.distribution == "Ubuntu"

- name: Install asdf dependencies for MacOS
  ansible.builtin.package:
    name: '{{ asdf_macos_dependencies }}'
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Clone asdf repo
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '{{ asdf_dir }}'
    version: v0.12.0

- name: Insert asdf config .zshrc
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir }}/.zshrc'
    insertbefore: '# Completion'
    marker: '{mark} asdf'
    marker_begin: '# BEGIN'
    marker_end: '# END'
    block: |
      # Load asdf
      . "$ASDF_DIR/asdf.sh"
      # Append completions to fpath
      fpath=(${ASDF_DIR}/completions $fpath)

- name: Insert asdf env variables into .zshenv
  ansible.builtin.blockinfile:
    path: '{{ ansible_facts.user_dir }}/.zshenv'
    marker: '{mark} asdf'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: |
      export ASDF_DIR={{ asdf_dir }}
      export ASDF_DATA_DIR={{ asdf_data_dir }}

#############
# Languages #
#############
- name: Install dependencies for Ubuntu
  become: true
  ansible.builtin.package:
    name:
      # Nodejs
      # Nodejs build: https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms
      - python3
      - g++
      - make
      - python3-pip
      # Rust
      - build-essential
    state: present
  when: ansible_facts.distribution == "Ubuntu"

- name: Install nodejs dependencies for MacOS
  ansible.builtin.package:
    name:
      # Nodejs
      - python3
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install nodejs
  vars:
    name: nodejs
    version: 18.17.0
  ansible.builtin.shell: |
    . "{{ asdf_dir }}"/asdf.sh
    asdf plugin add {{ name }} || true
    asdf install {{ name }} {{ version }}
    asdf global {{ name }} {{ version }}

- name: Install rust
  vars:
    name: rust
    version: 1.71.1
  ansible.builtin.shell: |
    . "{{ asdf_dir }}"/asdf.sh
    asdf plugin add {{ name }} || true
    asdf install {{ name }} {{ version }}
    asdf global {{ name }} {{ version }}
