---
- name: Install asdf dependencies for Debian
  become: true
  ansible.builtin.package:
    name: '{{ asdf_debian_dependencies }}'
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install asdf dependencies for Darwin
  ansible.builtin.package:
    name: '{{ asdf_darwin_dependencies }}'
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Clone asdf repo
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '{{ asdf_dir }}'
    version: v0.12.0

- name: Insert asdf config .zshrc
  ansible.builtin.blockinfile:
    path: '{{ zsh_dir }}/.zshrc'
    marker: '{mark} asdf'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: |
      # Load asdf
      . "$ASDF_DIR/asdf.sh"
      # append completions to fpath
      fpath=(${ASDF_DIR}/completions $fpath)
      # initialise completions with ZSH's compinit
      autoload -Uz compinit && compinit

- name: Insert asdf env variables into .zshenv
  ansible.builtin.blockinfile:
    path: '{{ ansible_facts.user_dir }}/.zshenv'
    marker: '{mark} asdf'
    marker_begin: '\n# BEGIN'
    marker_end: '# END'
    block: |
      export ASDF_DIR={{ asdf_dir }}
      export ASDF_DATA_DIR={{ asdf_data_dir }}

########################################
################ Nodejs ################
########################################
# Plugin: https://github.com/asdf-vm/asdf-nodejs
# Nodejs build: https://github.com/nodejs/node/blob/main/BUILDING.md#building-nodejs-on-supported-platforms
- name: Install nodejs dependencies for Debian
  become: true
  ansible.builtin.package:
    name:
      - python3
      - g++
      - make
      - python3-pip
    state: present
  when: ansible_facts.os_family == "Debian"

# TODO
# xcode-select & python 3
- name: Install nodejs dependencies for Darwin
  ansible.builtin.command: xcode-select --install
  when: ansible_facts.os_family == "Darwin"
  # when: ansible_facts.distribution == "MacOSX"

- name: Install nodejs
  vars:
    name: nodejs
    version: 18.17.0
  ansible.builtin.shell: |
    . "{{ asdf_dir }}"/asdf.sh
    asdf plugin add {{ name }} || true
    asdf install {{ name }} {{ version }}
    asdf global {{ name }} {{ version }}
