---
- name: Install oh-my-zsh dependencies
  become: '{{ ansible_facts.distribution != "MacOSX" }}'
  ansible.builtin.package:
    name: '{{ oh_my_zsh_dependencies }}'
    state: present

# Inspired from https://github.com/gantsign/ansible-role-oh-my-zsh
- name: Install oh-my-zsh
  # https://github.com/ohmyzsh/ohmyzsh#unattended-install
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
  args:
    creates: '{{ ansible_facts.user_dir }}/.oh-my-zsh'

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: '{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: Set zsh as the default shell
  become: true
  ansible.builtin.shell: |
    if [[ {{ ansible_facts.user_shell | basename != "zsh" }} ]]
    then
      chsh -s $(which zsh) {{ ansible_facts.user_id }}
    fi

- name: Create a default zsh configuration
  template:
    src: zshrc.j2
    dest: '{{ ansible_facts.user_dir }}/.zshrc'
    backup: true
    mode: 'u=rw,go=r'
