---
- name: Install tmux
  become: '{{ ansible_facts.distribution != "MacOSX" }}'
  ansible.builtin.package:
    name: tmux
    state: present

- name: Create a default tmux configuration
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
    backup: true
    mode: 'u=rw,go=r'

- name: Install tpm plugin manager
  ansible.builtin.command: 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'
  args:
    creates: ~/.tmux/plugins/tpm
