---
- name: Install tmux
  become: '{{ ansible_facts.distribution != "MacOSX" }}'
  ansible.builtin.package:
    name: tmux
    state: present

- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ tmux_dir }}'
    state: directory

- name: Create a default tmux configuration
  ansible.builtin.template:
    src: tmux/tmux.conf.j2
    dest: '{{ tmux_dir }}/tmux.conf'
    backup: true
    mode: 'u=rw,go=r'

- name: Install tpm plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: '{{ tmux_dir }}/plugins/tpm'
