---
vscodium_extensions:
  - bradlc.vscode-tailwindcss
  - budparr.language-hugo-vscode
  - bungcip.better-toml
  - catppuccin.catppuccin-vsc
  - catppuccin.catppuccin-vsc-icons
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - golang.go
  - hookyqr.beautify
  - josee9988.minifyall
  - mikestead.dotenv
  - ms-python.pylint
  - ms-python.python
  - ritwickdey.liveserver
  - shardulm94.trailing-spaces
  - shd101wyy.markdown-preview-enhanced
