---
- name: Install alacritty for Ubuntu
  become: true
  community.general.snap:
    name: alacritty
    channel: edge
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install alacritty for MacOS
  community.general.homebrew_cask:
    name: alacritty
    state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ alacritty_dir }}'
    state: directory

# Starting from v0.13, the YAML config file changed to a TOML file
- name: Create a default alacritty configuration file
  ansible.builtin.template:
    src: alacritty/alacritty.toml.j2
    dest: '{{ alacritty_dir }}/alacritty.toml'
    backup: true
    mode: 'u=rw,go=r'

- name: Install alacritty theme
  ansible.builtin.git:
    repo: 'https://github.com/catppuccin/alacritty'
    dest: '{{ alacritty_dir }}/catppuccin'
