---
- name: Install alacritty for Ubuntu
  become: true
  community.general.snap:
    name: alacritty
    channel: edge
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install alacritty for MacOS
  community.general.homebrew_cask:
    name: alacritty
    state: present
  # ansible.builtin.package:
  #   name: alacritty
  #   state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ alacritty_dir }}'
    state: directory

# Starting with version 0.13, the config file is a toml file
- name: Create a default alacritty configuration file
  ansible.builtin.template:
    src: alacritty/alacritty.yml.j2
    dest: '{{ alacritty_dir }}/alacritty.yml'
    backup: true
    mode: 'u=rw,go=r'

- name: Install alacritty theme
  ansible.builtin.git:
    repo: 'https://github.com/catppuccin/alacritty'
    dest: '{{ alacritty_dir }}/catppuccin'
