---
- name: Install alacritty for Debian
  become: true
  community.general.snap:
    name: alacritty
    channel: edge
    classic: true
  when: ansible_facts.os_family == 'Debian'

- name: Install alacritty for Darwin
  ansible.builtin.package:
    name: alacritty
    state: present
  when: ansible_facts.os_family == 'Darwin'
