---
- name: Install postman for Ubuntu
  become: true
  community.general.snap:
    name: postman
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install postman for MacOS
  community.general.homebrew_cask:
    name: postman
    state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Install stats for MacOS
  ansible.builtin.package:
    name: stats
    state: present
  when: ansible_facts.distribution == 'MacOSX'

- name: Install sourcetree for MacOS
  community.general.homebrew_cask:
    name: sourcetree
    state: present
  when: ansible_facts.distribution == 'MacOSX'
