---
- name: Install neovim for Debian
  become: true
  community.general.snap:
    name: nvim
    classic: true
  when: ansible_facts.os_family == 'Debian'

- name: Install neovim for Darwin
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_facts.os_family == 'Darwin'

- name: Ensure directories exist
  ansible.builtin.file:
    path: '{{ nvim_dir }}/{{ item }}'
    state: directory
  loop:
    - plugin
    - after/plugin
    - lua/user

- name: Create a neovim init file
  ansible.builtin.template:
    src: nvim/init.lua.j2
    dest: '{{ nvim_dir }}/init.lua'
    mode: 'u=rw,go=r'

- name: Create modules config files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ nvim_dir }}/lua/user/{{ item | basename | regex_replace("\.j2$", "")}}'
    mode: 'u=rw,go=r'
  with_fileglob: templates/nvim/lua/user/*.j2
