---
- name: Install neovim
  become: true
  community.general.snap:
    name: nvim
    classic: true
  when: ansible_facts.os_family == 'Debian'

- name: Install neovim
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_facts.os_family == 'Darwin'

- name: Ensure directories exist
  file:
    path: '{{ ansible_facts.user_dir }}/.config/nvim/{{ item }}'
    state: directory
  loop:
    - plugin
    - after/plugin
    - lua/user

- name: Create a neovim init file
  template:
    src: nvim/init.lua.j2
    dest: '{{ ansible_facts.user_dir }}/.config/nvim/init.lua'
    mode: 'u=rw,go=r'

- name: Create modules config files
  template:
    src: '{{ item }}'
    dest: '{{ ansible_facts.user_dir }}/.config/nvim/lua/user/{{ item | basename | regex_replace("\.j2$", "")}}'
    mode: 'u=rw,go=r'
  with_fileglob: templates/nvim/lua/user/*.j2
