---
- name: Install fonts dependencies
  become: '{{ ansible_facts.distribution != "MacOSX" }}'
  ansible.builtin.package:
    name: '{{ font_dependencies }}'
    state: present

- name: Setting font path for Debian
  ansible.builtin.set_fact: font_path="{{ ansible_facts.user_dir }}/.local/share/fonts"
  when: ansible_facts.os_family == 'Debian'

- name: Setting font path for Darwin
  ansible.builtin.set_fact: font_path="{{ ansible_facts.user_dir }}/Library/Fonts"
  when: ansible_facts.os_family == 'Darwin'

- name: Install fonts
  ansible.builtin.shell: curl -Lo {{ item.filename }}.ttf https://github.com/ryanoasis/nerd-fonts/raw/v3.0.2/patched-fonts/{{ item.path }}/{{ item.filename }}.ttf
  args:
    chdir: '{{ font_path }}'
    creates: '{{ item.filename }}.ttf'
  loop: '{{ font_list }}'
